id: QmWC5sPUBW6Y4xT23TvLLQHa1Hjs6uEZAGU22tmKDFgejp
description: Returns pong to a ping over http
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /ping4
domains:
    - GeneratedDomain
source: .
execution:
    timeout: 10s
    memory: 10MB
    call: ping
